version: '3.8'

services:
  palworld:
    image: palworld-server
    container_name: palworld-server
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
      - "27015:27015/tcp"
    volumes:
      - ./palworld-data:/home/steam/palworld-server
      - ./scripts:/scripts
    environment:
      - RCON_ENABLED=true
      - RCON_PORT=27015
      - RCON_PASSWORD=your_secure_password_here
      - TZ=UTC
